kind: Deployment
apiVersion: apps/v1
metadata:
  name: dror-andal-prod
  namespace: hands-on-jenkins-app
spec:
  replicas: 1
  selector:
      matchLabels:
          app: dror-andal
          env: dev
  template:
    metadata:
      name: dror-andal-prod
      labels:
        app: dror-andal
        env: dev
    spec:
      containers:
      - name: dror-andal-prod
        image: stavco9/blabla
        #resources:
          #limits:
          #  memory: "500Mi"
        #    cpu: "100m"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3      
        ports:
        - name: app
          containerPort: 5000