apiVersion: v1
kind: Service
metadata:
  name: lior-kipod-dev
  namespace: hands-on-jenkins-app
  labels:
    app: lior-kipod
    env: dev
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: lior-kipod
    env: dev