apiVersion: v1
kind: Service
metadata:
  name: hands-on-jenkins-app-dev
  namespace: hands-on-jenkins-app
  labels:
    app: hands-on-jenkins
    env: dev
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: hands-on-jenkins